version: 2

jobs:

  build:
    
    working_directory: ~/sample-java

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn clean
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn install -DskipTests=true 
	
      - store_artifacts:
	  path: target
  deploy:

    working_directory: ~/sample-java

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

workflows:

  version: 2

  build-and-deploy:

    jobs:

      - build

      - deploy:
          type: approval
          requires:
            - build

