version: 2

jobs:

  build:
    
    working_directory: ~/sample-java

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    branches:
      only:
        - branch1

    steps:
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn clean
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn install -DskipTests=true 

      - persist_to_workspace:
          root: ~/sample-java
          paths:
            - target/java-archive-1.0-SNAPSHOT.jar

  deploy:

    working_directory: ~/sample-java

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - attach_workspace:
          at: ~/sample-java

      - store_artifacts:
          path: target/java-archive-1.0-SNAPSHOT.jar
 
      - store_test_results:
          path: target/surefire-reports

workflows:

  version: 2

  build-and-deploy:

    jobs:

      - build

      - deploy:
          requires:
            - build
